package ru.job4j.tracker;
/**
 * Application item
 * @author Andrei Pashchenko.
 * @version 1
 * @since 16.02.2019
 */
public class Item {
    private String id;
    private String name;
    private String desc;
    private long created;
    private String[] comments;

    public Item(String name, String desc, long created) {
        this.name = name;
        this.desc = desc;
        this.created = created;
    }
    /**
     * @return item Id field.
     */
    public String getId() {
        return this.id;
    }
    /**
     * Setting item Id.
     * @param id Id (generated by Tracker).
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * @return Name field.
     */
    public String getName() {
        return name;
    }
}
